SELECT*FROM MONEY;
SELECT*FROM MEMBER;
SELECT*FROM CUSTOMER;
SELECT*FROM INOUT;
SELECT*FROM ACCOUNT;
SELECT*FROM CATEGORY;
SELECT*FROM TOTALMONEY;

INSERT INTO TOTALMONEY(TM_MMCODE,TM_MAX,TM_MIN) 
VALUES('1004',0,0);

INSERT INTO INOUT(IO_CODE,IO_MMCODE,IO_DATE,IO_LOCODE,IO_ACCODE,IO_CUCODE,IO_MONEY,IO_MEMO)
VALUES('10001','1001',DEFAULT,'1','301','1001','20000','엽떡사먹음(체크카드)');
INSERT INTO INOUT(IO_CODE,IO_MMCODE,IO_DATE,IO_LOCODE,IO_ACCODE,IO_CUCODE,IO_MONEY,IO_MEMO)
VALUES('10002','1001',DEFAULT,'2','101','1001','20000','엽떡사먹음(체크카드)');

INSERT INTO INOUT(IO_CODE,IO_MMCODE,IO_DATE,IO_LOCODE,IO_ACCODE,IO_CUCODE,IO_MONEY,IO_MEMO)
VALUES('10003','1001',DEFAULT,'1','302','1002','1000','버스(체크카드)');
INSERT INTO INOUT(IO_CODE,IO_MMCODE,IO_DATE,IO_LOCODE,IO_ACCODE,IO_CUCODE,IO_MONEY,IO_MEMO)
VALUES('10004','1001',DEFAULT,'2','101','1002','1000','버스(체크카드)');

INSERT INTO INOUT(IO_CODE,IO_MMCODE,IO_DATE,IO_LOCODE,IO_ACCODE,IO_CUCODE,IO_MONEY,IO_MEMO)
VALUES('10005','1001',DEFAULT,'1','301','1001','12000','찜닭사먹음(체크카드)');
INSERT INTO INOUT(IO_CODE,IO_MMCODE,IO_DATE,IO_LOCODE,IO_ACCODE,IO_CUCODE,IO_MONEY,IO_MEMO)
VALUES('10006','1001',DEFAULT,'2','101','1001','12000','찜닭사먹음(체크카드)');

INSERT INTO ACCOUNT(AC_CODE,AC_NAME,AC_CACODE,AC_LOCODE) 
VALUES('102','보통예금','100','2');
INSERT INTO ACCOUNT(AC_CODE,AC_NAME,AC_CACODE,AC_LOCODE) 
VALUES('302','교통비','300','1');

INSERT INTO CUSTOMER(CU_CODE,CU_NAME,CU_MOCODE,CU_MMCODE) 
VALUES('1001','엽떡','101','1001');
INSERT INTO CUSTOMER(CU_CODE,CU_NAME,CU_MOCODE,CU_MMCODE) 
VALUES('1002','버스','102','1001');
INSERT INTO CUSTOMER(CU_CODE,CU_NAME,CU_MOCODE,CU_MMCODE) 
VALUES('1003','두찜','101','1001');

INSERT INTO MONEY(MO_MMCODE,MO_CODE,MO_NAME,MO_TOTAL) 
VALUES('1001','102','교통','100000');

INSERT INTO MONEY(MO_MMCODE,MO_CODE,MO_NAME,MO_TOTAL) 
VALUES('1001','104','경조사','400000');
INSERT INTO MONEY(MO_MMCODE,MO_CODE,MO_NAME,MO_TOTAL) 
VALUES('1001','105','경조사2','400000');
commit;

/* 예산 카테고리별 금액 가져오기 */
-- 한번이라도 INOUT에 등록된 예산항목들 가져오기
CREATE OR REPLACE VIEW CABUDGET
AS;
SELECT  MO_MMCODE AS MMCODE,
        MO_CODE AS MOCODE,
        MO_NAME AS MONAME,
        MO_TOTAL AS MOTOTAL,
        TM_MAX AS TMMAX,
        TM_MIN AS TMMIN,
        SUM(IO_MONEY)/2 AS SPENDMONEY
FROM INOUT INNER JOIN CU ON IO_CUCODE = CU_CODE
           INNER JOIN MO ON CU_MOCODE = MO_CODE AND MO_MMCODE = IO_MMCODE
           INNER JOIN TM ON TM_MMCODE = MO_MMCODE
GROUP BY MO_MMCODE, MO_NAME, MO_CODE, MO_TOTAL, TM_MAX, TM_MIN;


/* XML 구문 */
SELECT  MMCODE,
        MOCODE,
        MONAME,
        TO_CHAR(MOTOTAL,'FM999,999,999,999') AS MOTOTAL,
        TO_CHAR(SPENDMONEY,'FM999,999,999,999') AS SPENDMONEY,
        ROUND((SPENDMONEY / MOTOTAL)*100) AS PERBG
FROM CABUDGET WHERE MMCODE = '1001';

-- 한번도 지출한적 없는 예산항목 
SELECT  MO_MMCODE AS MMCODE,
        MO_CODE AS MOCODE,
        MO_NAME AS MONAME,
        TO_CHAR(MO_TOTAL,'FM999,999,999,999') AS MOTOTAL
FROM  MONEY
WHERE MO_CODE NOT IN (SELECT MOCODE FROM CABUDGET);

/* 내가 설정한 총 예산, 내가 설정한 최소예산, 지금까지 사용한 총 예산 가져오기 */ 
/* 내가 설정한 총 예산 */
SELECT TO_CHAR(TMMAX,'FM999,999,999,999')
FROM CABUDGET WHERE MMCODE = '1001'
GROUP BY TMMAX;
/* 내가 설정한 최소예산 */
SELECT TO_CHAR(TMMIN,'FM999,999,999,999')
FROM CABUDGET WHERE MMCODE = '1001'
GROUP BY TMMIN;
/* 내가 지금까지 사용한 총 예산*/
SELECT TO_CHAR(SUM(SPENDMONEY),'FM999,999,999,999') AS SPENDTOTALMONEY
FROM CABUDGET WHERE MMCODE = '1001'
GROUP BY TMMAX;

/* 클라이언트에서 입력받은 총 예산값으로 현재 총 예산값 변경하기 */
UPDATE TM SET TM_MAX = '1000000' WHERE TM_MMCODE = '1001';

/* 예산항목 삭제 */
-- 삭제하려면 CU에서 먼저 삭제하고 MO에서 삭제해야함
-- 0.먼저 CUSTOMER에서 MOCODE가 사용되고있는지 확인
SELECT COUNT(*)
FROM CUSTOMER WHERE CU_MOCODE='MOCODE';
-- 1.존재O
-- 1.1 CU에서 NULL로 바꾸기
UPDATE CUSTOMER SET CU_MOCODE='' WHERE CU_MOCODE='MOCODE';
-- 1.2 MONEY에서 삭제
DELETE FROM MONEY WHERE MO_CODE = 'MOCODE';

-- 2.존재X
-- 2.1 MONEY에서 삭제
DELETE FROM MONEY WHERE MO_CODE = 'MOCODE';

/* 예산항목 추가 */
-- MOCODE 최대값or최초값 가져오기
SELECT NVL (MAX(MO_CODE)+1 , 101 )
FROM MONEY WHERE MO_MMCODE= '1001';
-- 예산항목 insert
INSERT INTO MO(MO_MMCODE,MO_CODE,MO_NAME,MO_TOTAL)
VALUES(#{MMCODE},#{MOCODE},#{MONAME},MOTOTAL);

/* 예산항목 수정 */
UPDATE MO SET MO_NAME = #{MONAME}, MO_TOTAL = #{MOTOTAL} WHERE MO_MMCODE=#{MMCODE} AND MO_CODE=#{MOCODE};

/* TS(총설정예산-현재지출액) < 최소설정예산 일때 경고해주기 */
SELECT  TO_CHAR((TMMAX - SUM(SPENDMONEY)),'FM999,999,999,999') AS STATUS,
        TO_CHAR(TMMAX,'FM999,999,999,999'),
        TO_CHAR(TMMIN,'FM999,999,999,999')
FROM CABUDGET WHERE MMCODE = '1001'
GROUP BY TMMAX,TMMIN;

